version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  nodeapp:
    image: mtgo-price-tracker
    container_name: nodeapp
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    environment:
      DB_URL: mongodb://mongo:27017/cardflipmarket_db
      PORT: 5000
      NODE_ENV: PRODUCTION
    volumes:
      - nodeapp-data:/app
    command: npm run server
    restart: always

volumes:
  mongo-data:
  nodeapp-data: 
